import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "./components/Navbar";
import Welcome from "./components/Welcome";
import About from "./components/About";
import Footer from "./components/Footer";
import Createbusinessownerpage from "./components/Createbusinessownerpage";
// import Header from "./components/Header";
// import { Head } from "next/document";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WE~HELP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return ( 
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        
        <Navbar />
       <Welcome />
       <Createbusinessownerpage />
       <About />
       <Footer />
        {children}
       
        </body>
    </html>
      </ClerkProvider>
  );
}
